import requests

TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJzcmluaWRoaWFrdXRob3RhMjRAZ21haWwuY29tIiwiZXhwIjoxNzgxNzY4MDA3LCJpYXQiOjE3ODE3NjcxMDcsImlzcyI6IkFmZm9yZCBNZWRpY2FsIFRlY2hub2xvZ2llcyBQcml2YXRlIExpbWl0ZWQiLCJqdGkiOiJmOGU2M2Q4OS0wOTA1LTRkMjYtYTQyNy1hZDAxYWFkYTA5ZjMiLCJsb2NhbGUiOiJlbi1JTiIsIm5hbWUiOiJha3V0aG90YSBzcmluaWRoaSIsInN1YiI6IjNiMmE3YTFiLTFlZTItNDdmMi04OGRhLTUwMWY1ZjA5YWZhMyJ9LCJlbWFpbCI6InNyaW5pZGhpYWt1dGhvdGEyNEBnbWFpbC5jb20iLCJuYW1lIjoiYWt1dGhvdGEgc3JpbmlkaGkiLCJyb2xsTm8iOiIyMzAzYTUxMTMxIiwiYWNjZXNzQ29kZSI6ImJEcmVBcSIsImNsaWVudElEIjoiM2IyYTdhMWItMWVlMi00N2YyLTg4ZGEtNTAxZjVmMDlhZmEzIiwiY2xpZW50U2VjcmV0IjoiZ1VzeXRoUURBbXNIY3BXWCJ9.ge6Lhk1-fI82f3ygTdpHB3ZnGEwNU6NYyGsIXupjLAM"

headers = {
    "Authorization": f"Bearer {TOKEN}"
}

response = requests.get(
    "http://4.224.186.213/evaluation-service/depots",
    headers=headers
)

print(response.json())