import requests

API_URL = "http://4.224.186.213/evaluation-service/notifications"

TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJzcmluaWRoaWFrdXRob3RhMjRAZ21haWwuY29tIiwiZXhwIjoxNzgxNzcwNDM1LCJpYXQiOjE3ODE3Njk1MzUsImlzcyI6IkFmZm9yZCBNZWRpY2FsIFRlY2hub2xvZ2llcyBQcml2YXRlIExpbWl0ZWQiLCJqdGkiOiI4ZTQ0MDdkYS03M2I0LTQ2M2QtYTZkZS1lZGU0MWJhNTEzOGQiLCJsb2NhbGUiOiJlbi1JTiIsIm5hbWUiOiJha3V0aG90YSBzcmluaWRoaSIsInN1YiI6IjNiMmE3YTFiLTFlZTItNDdmMi04OGRhLTUwMWY1ZjA5YWZhMyJ9LCJlbWFpbCI6InNyaW5pZGhpYWt1dGhvdGEyNEBnbWFpbC5jb20iLCJuYW1lIjoiYWt1dGhvdGEgc3JpbmlkaGkiLCJyb2xsTm8iOiIyMzAzYTUxMTMxIiwiYWNjZXNzQ29kZSI6ImJEcmVBcSIsImNsaWVudElEIjoiM2IyYTdhMWItMWVlMi00N2YyLTg4ZGEtNTAxZjVmMDlhZmEzIiwiY2xpZW50U2VjcmV0IjoiZ1VzeXRoUURBbXNIY3BXWCJ9.WBcRiVVI6-zKJV7Ef-V3TS7vS18QhtMDnwpnAJHBFUo"

headers = {
    "Authorization": f"Bearer {TOKEN}"
}

response = requests.get(API_URL, headers=headers)

print(response.status_code)
print(response.text)